
security:
  oauth2:
    client:
      client-id: app
      client-secret: secret
      scope: read
      #auto-approve-scopes: '.*'
      access-token-uri: http://localhost:9090/oauth/token
      user-authorization-uri: http://localhost:9090/oauth/authorize
      grant-type: authorization_code
    resource:
      userInfoUri: http://localhost:9090/me
    sso:
      login-path: /login
logging:
  level:
    org.springframework.security: DEBUG

server:
  port: 9091
  session:
    cookie:
      name: OAUTH2SESSION